### ISSUE TITLE
(SOQL Query Builder) General Feature requests

### ISSUE THREAD

**Issue by paustint** [forcedotcom/soql-tooling#124]
**Is your feature request related to a problem? Please describe.**
General product feature requests

**Describe the solution you'd like**

1. I want to to be able to see more fields at once (e.x. expand fields section)
1. Fields should be ordered alphabetically, but Id and Name should be the first two fields, always - impossible to find what I need
1. I want to see the field label and field type (e.x. Account Name, Name, Text)
1. I want to traverse relationships (e.x. let me build Account.Owner.Name)
1. I want to use Tooling API objects/fields and run Tooling queries
1. When lots of fields are selected, the output table should scroll horizontally

**Describe alternatives you've considered**
Alternatives are to use other tooling, such as https://getjetstream.app/ - but sometimes it is nice not to have to leave my development environment.

**Additional context**
none

**Comment by smaddox-sf** [comment]
Thank you all for trying SOQL Builder and providing feedback.  Items 1 & 2 from the original post have been merged and will be released in the next couple weeks.

I broke out the remaining feedback to 1 issue per topic.  This helps us stay organized and have focused discussion for each. Here’s the issue # per topic:

- #136 - _I want to see the field label and field type (e.x. Account Name, Name, Text)_ 
- #137 - _I want to traverse relationships (e.x. let me build Account.Owner.Name)_
- #84 - _I want to use Tooling API objects/fields and run Tooling queries_
- #138 - _When lots of fields are selected, the output table should scroll horizontally_
- #135 - Edit SOQL text from within the builder.
- #89 - Select all fields, select all non-system fields, etc

@loktevich - We’ve added a quick toggle to let you swap between the text editor and the Builder.  (screenshot below) This gives you a quick way to add more complexity to queries that the Builder doesn't provide. Curious if you've tried this?  Please respond on #135 if you have more feedback.

![image](https://user-images.githubusercontent.com/59572234/106206508-0f424000-6175-11eb-95c6-147d0ccd3bc3.png)


Please weigh in on the individual issues if you have other feedback on these items.   Thank you!
