### ISSUE TITLE
Suggestion on Fields and WHERE clause boxes

### ISSUE THREAD

**Issue by yuvrajmst** [forcedotcom/soql-tooling#133]
Hello,
Recently I just installed this extension to my workspace: **SOQL Builder for Visual Studio Code**. This is really amazing and, also waited for this update. I have some feedback which has been mentioned below.
![image](https://user-images.githubusercontent.com/24931586/106098486-1e1df800-615f-11eb-915c-31a2ae905a6a.png)

1. It would be better **Fields** box have draggable window, So we can have a wide views in the Fields selection box and also it will be more easier to us select particular field which might have large number of fields for some objects.
2. As per the above image, you can see in image(highlighted as 2 in red circle) there is no WHERE clause in the SOQL Query. It would be better to create another box for WHERE clause like **ORDERBY** and **LIMIT** or make SOQL Query box as editable so the developer can add their WHERE clause to the query.

**Comment by smaddox-sf** [comment]
Hi @yuvrajmst - Thanks for trying out SOQL Builder and giving us feedback!  We're working on both of these areas:

1 - We just merged updates to the Fields box and will be releasing that in the coming weeks.  [If you'd like a preview, check out the short video on this PR](https://github.com/forcedotcom/soql-tooling/pull/130).

2-  UI for the where clause is in flight and will also ship in the next few weeks.

**Comment by smaddox-sf** [comment]
Hi @yuvrajmst - We added the WHERE clause last week and also made improvements to the Fields and Objects selection.  Download the latest version and check it out!  I'm closing this issue, but feel free to open new ones if you have additional feedback.  Thank you!
