### ISSUE TITLE
Allow NULL to be a valid input value

### ISSUE THREAD

**Issue by praksb** [forcedotcom/soql-tooling#173]
### Summary

I am noticing that using "NULL" as a value in the Filter clause causes some unexpected validation errors to show up in the builder

### Steps To Reproduce:

1.  Pick "Contact" as the SObject Field
1.  Pick a field of type String" like "AssistantName"  and pick any operator
1. Type in "NULL" as the Value.

### Expected result

It should not show validation error

### Actual result

Validation error which says "Enclose value in single quotes" 

### Additional information

Also, try a field of a different type like Datetime and use NULL as the value and you'll get a validation error with a different message

**Comment by smaddox-sf** [comment]
Duplicate #241
