### ISSUE TITLE
When modifying the Field in the filter clause it switches back silently to the previously picked field when editing the value

### ISSUE THREAD

**Issue by praksb** [forcedotcom/soql-tooling#175]
See the video below, I am trying to switch the field from "AssistantName" to "CreatedDate" and while I am editing the value the field silently switches back to "AssistantName".

https://user-images.githubusercontent.com/10749920/106965728-e97ae500-66f8-11eb-8060-0e095c32f9f4.mov

**Comment by jonnyhork** [comment]
I think this is related to #172  and I think both will be fixed with PR #168

**Comment by jonnyhork** [comment]
I looked into this and it seems we are just missing the event handler `onoption__selection={handleSelectionEvent}`. Adding that now updates the model for me.
