### ISSUE TITLE
General feature request[Query Builder] to copy the Query

### ISSUE THREAD

**Issue by sarava77** [forcedotcom/soql-tooling#221]
**Is your feature request related to a problem? Please describe.**
Its quite easy to build and execute the query. once I build the query I don't have a option to copy the query and use it in my apex. It would be really good if we have a clone button just beside the 'Run Query' button.

**Describe the solution you'd like**
It would be really good if we have button called 'Copy' beside the 'Run Query' button.

**Describe alternatives you've considered**
I need to select the query.

**Additional context**
None

**Comment by smaddox-sf** [comment]
We've added a toggle to let you swap to the editor.  From there, you can copy or edit the query if you want to add more complex conditions.  We don't plan to add an explicit copy button to the Builder at this time.  See https://developer.salesforce.com/tools/vscode/en/soql/soql-builder/#switch-between-soql-builder-and-text-editor for details on the toggle.
