### ISSUE TITLE
SOQL Language Server - OFFSET and LIMIT Context Restriction

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/soql-tooling#225]
### Summary

OFFSET and LIMIT token appear in contexts where they should not be available.

### Steps To Reproduce:

1.  Type in query `SELECT Title FROM Contact ORDER BY Title ASC NULLS FIRST OFFSET `
1.  Bring up the auto completion list with Ctr+Space.

### Expected result

OFFSET should not be available as an auto-completion option. Likewise, if the token was LIMIT then LIMIT should not be available as an auto-completion option.

### Actual result

OFFSET should not be available from the auto-completion list if the last token was OFFSET.
<img width="1602" alt="Invalid OFFSET token in auto complete" src="https://user-images.githubusercontent.com/45604118/67503934-c6ccd600-f645-11e9-8ba3-4bbc74688c6c.png">

LIMIT should not be available from the auto-completion list if the last token was LIMIT.
<img width="1512" alt="Invalid LIMIT token in auto complete" src="https://user-images.githubusercontent.com/45604118/67503958-cfbda780-f645-11e9-90ae-0bca824ad521.png">

**Comment by smaddox-sf** [comment]
Fixed in the SOQL LSP.  (also, ctrl+space is no longer needed to trigger the completions - they appear automatically now)
