### ISSUE TITLE
SOQL Language Server - GROUP BY Token Restrictions

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/soql-tooling#227]
### Summary

GROUP BY should not be an auto complete option if we already have GROUP BY in the proceeding token (for example ROLLUP/CUBE).

### Steps To Reproduce:

1.  Type query `SELECT Title, COUNT(Name) FROM Contact GROUP BY ROLLUP ` from a .soql file.
1.  Run the auto-completion with Ctr+Space.

### Expected result

When I have a query like the following, I would not expect to see the 'GROUP BY' token.
    `SELECT Title, COUNT(Name) FROM Contact GROUP BY ROLLUP `
    `SELECT Title, COUNT(Name) FROM Contact GROUP BY CUBE `

### Actual result

For query `SELECT Title, COUNT(Name) FROM Contact GROUP BY ROLLUP ` GROUP BY is an auto-complete option.
<img width="1619" alt="GROUP BY token is available after GROUP BY ROLLUP" src="https://user-images.githubusercontent.com/45604118/67505774-1e207580-f649-11e9-97ef-918b1b069df9.png">

For query `SELECT Title, COUNT(Name) FROM Contact GROUP BY CUBE ` GROUP BY is an auto-completion option.
<img width="1509" alt="GROUP BY token is available after GROUP BY CUBE" src="https://user-images.githubusercontent.com/45604118/67506436-48266780-f64a-11e9-9e8c-713956d047f6.png">

**Comment by smaddox-sf** [comment]
Fixed in the SOQL LSP
