### ISSUE TITLE
SOQL Language Mode

### ISSUE THREAD

**Issue by rmoodySIS** [forcedotcom/soql-tooling#229]
Whenever I save .soql files, the Language Mode automatically changes to Apex. Unfortunately, the Apex language mode doesn't check for any syntax errors. 

So our only option is to develop in SQL, then switch to SOQL so VSCode isn't reporting problems when using things like "NEXT_N_DAYS".

Ideally, either the Apex Language Mode would check for syntax errors, or a separate SOQL language mode would be provided for this purpose.

**Comment by smaddox-sf** [comment]
We have created the initial SOQL language server that is mapped to .soql files.  We still have work to do to flesh it out and enable it for SOQL embedded in Apex.  It will be added the extension pack over time, but for now it's a standalone extension.  Check it out and let us know if you have feedback!  https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-soql
