### ISSUE TITLE
Issue with typing in the SOQL Builder filter section

### ISSUE THREAD

**Issue by angshumit** [forcedotcom/soql-tooling#240]
**OS and version**:
Windows 10 Enterprise

**VS Code Version**:
Version: 1.54.3 (user setup)

**SFDX CLI Version**:
Salesforce Query Editor v1.0.21
Salesforce Extension Pack v51.7.0
Salesforce CLI Integration v51.7.0

### Summary

In SOQL Builder mode, while typing in quickly in the 'Value' column in 'Filter' section, it keeps reverting back the last few key strokes. Example: I quickly typed in the text 'system admin' in the 'Value' column, it initially typed in the whole text, but then in about 1 second, the 'system admin' text changed back to 'system adm' or 'system ain' and so on. I observed that there is a lag between my typing and the query previewed in the 'SOQL Query' section, and whenever this lag falls about 2-3 characters behind what I am typing, it reverts back my typed in text

### Steps To Reproduce:

(this is how I got it)
1. Opened a .soql file in SOQL Builder mode
2. Filled up the 'From' field = User
3. Selected in the 'Fields' = Id, Name, Email
4. In the 'Filter' section, in the first row,
        Selected 'Field' = Profile_Name_vod__c
        Selected operator = not equal
        Typed in 'Value' column = 'System Administrator'

### Expected result

The text typed in the 'Value' column should be 'System Admin'

### Actual result

It reverts back my few key strokes.
Example: The text typed in the 'Value' column changed back to 'System Adm', on re-typing 'System Admin' the text changed to 'Admin Ain'

### Additional information

N/A

**Comment by dehru** [comment]
@angshumit Thanks for reporting this.  We have seen this in the past but thought we had corrected it.

**Comment by jonnyhork** [comment]
@angshumit Thanks again for reporting this to us. I have been unable to reproduce this issue using:
Windows 10
Salesforce Extension Pack v51.7.0
[SOQL v51.7.0](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-soql)

I notice you referenced [Salesforce Query Editor v1.0.21](https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor) in your report. This is produced by a third party and is not the official Salesforce SOQL Extension. Any issues using that extension should be reported [here](https://github.com/AllanOricil/SOQL-Editor-Issues).

Can you please verify you have the correct extension installed and which one you see this issue in?

Thanks!
