### ISSUE TITLE
Language Server Reports unclearable problems in existing SOQL files

### ISSUE THREAD

**Issue by pogilvie** [forcedotcom/soql-tooling#258]
**OS and version**:
MoacOS Big Sur Version 11.4 (20F71)

**VS Code Version**:
Version: 1.56.2

**SFDX CLI Version**:
sfdx-cli/7.103.0 darwin-x64 node-v14.17.0

### Summary

_Existing query collections files with .soql extension now report unclear-able problems._

### Steps To Reproduce:

1.  create a test.soql with the following contents
```sql
// a comment which says what this query does here
SELECT Id, Name
FROM Contact
WHERE Name = 'Jane Doe'


SELECT Id, Name
FROM Account
```

A problem is reported.  

mismatched input 'SELECT' expecting {<EOF>, 'and', 'or', 'with', 'offset', 'for', 'limit', 'group', 'order', 'update', 'bind'}
2. Close the file and Problem persists.     

### Expected result

It is the responsibility of extension builders to provide a way to clear unwanted problems w/o having to resort to restarting the editor.   

Please reviews comments from Microsoft on responsibilities of extension developers with regard to the problem pane.
https://github.com/microsoft/vscode/issues/66982

### Actual result
Unclear-able problem is reported in problem pane on existing .soql which I have been using with the existing execute selected text as soql command

### Additional information
Error persists even after deleting editor tab and deleting file from file system.   Restarting vscode is the only way to clear the error.

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/628688/120926857-762bb480-c693-11eb-90fe-6884badfc088.png">

**Comment by smaddox-sf** [comment]
Hi @pogilvie - Thanks for taking the time to submit feedback.   We will get this fixed so that the Problem(s) clears when the file is closed.  Otherwise, the only way way to clear the Problem is to limit the `.soql` file to a single query.  This is a current limitation of the parser - soql doesn't have a statement terminator to distinguish the end of one statement, so two queries is interpreted as a problem.

**Comment by dobladez** [comment]
On v52.1.0: the SOQL extension now clears the Problem(s) when the file is closed or deleted.

Thanks!
