### ISSUE TITLE
A New Tab Always opens, when VSCode is Loaded.

### ISSUE THREAD

**Issue by shivanshsen7** [forcedotcom/soql-tooling#259]
**OS and version**:
WIn10 (Windows_NT x64 10.0.19043)
**VS Code Version**:
1.5.7
**SFDX CLI Version**:
  sfdx-cli/7.106.3 win32-x64 node-v14.17.0

### Summary

A new Tab opens-up, every time vscode is loaded, 
### Steps To Reproduce:

1.  Open VSCode
2. Voila, A new Tab is opened. with releas notes.

### Expected result

No New Tab should be opened for release notes, unless Extenstion is updated or i ask for release notes.
### Actual result

New tab with release notes opened everytime,

### Additional information
![image](https://user-images.githubusercontent.com/42974761/123194577-5d5d3480-d4c4-11eb-8f41-b7b63521b8e8.png)

**Comment by jonnyhork** [comment]
Hi @shivanshsen7, thanks for sharing this issue however the extension you are using is not the official Salesforce extension, I believe you are looking for this repo https://github.com/AllanOricil/salesforce-query-editor
