### ISSUE TITLE
Switch Between SOQL Builder and Text Editor button dissapeared

### ISSUE THREAD

**Issue by laszlo-foldi-attentioncrm** [forcedotcom/soql-tooling#292]
**OS and version**: Microsoft Windows [Version 10.0.22631.4112]

**VS Code Version**:
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**SFDX CLI Version**: @salesforce/cli/2.57.7 win32-x64 node-v18.16.0

### Summary

The button to switch from text view to SOQL Builder has disappeared from the GUI. I can still select to open the .soql file via the SOQL Builder or the Text Editor, but there is no button for it anymore.

### Steps To Reproduce:

1.  Open an existing or a new SFDX project
1.  Create a new or Open an existing soql file
2. Observe that the switch editors icon is missing

### Expected result

There should be a button for switching between the SOQL Builder and the text editor

### Actual result

There is no button, and only switching via the context menu is available (right click->"Open With..."->...)

### Additional information

Text Editor view
![image](https://github.com/user-attachments/assets/8a7793f8-ea20-45c5-8f1f-fa9236cf47da)

SOQL Builder view
![image](https://github.com/user-attachments/assets/3e903c61-396b-4870-88c3-0590c9b6a151)

**Comment by laszlo-foldi-attentioncrm** [comment]
Thanks, this seems to fix my issue. Strange, I've never changed the settings for this.

**Comment by jonnyhork** [comment]
A PR to set the file association by default has been created: **https://github.com/forcedotcom/code-builder-images/pull/471**
