### ISSUE TITLE
W-7987352: Soql Builder UX - Selecting an Object from the List - Needs Filter / Autocomplete Component

### ISSUE THREAD

**Issue by dehru** [forcedotcom/soql-tooling#39]
**Is your feature request related to a problem? Please describe.**
The list of objects available in the "From" dropdown is cumbersome.  It would be better to be able to filter that list with a text input box that provided autocomplete and suggestions.  Currently, the default select input, while functional, is overwhelmingly long.

**Describe the solution you'd like**
What i would like to have is a component that will show all the available selections, but also allow me to type and that would filter down the selections to match my typing.  It should also offer the top match so that when i hit enter, i don't have to leave my keyboard or use the mouse.  

**Additional context**
Google search as an example of the UX I'd like to see.  

<img width="656" alt="Screen Shot 2020-10-22 at 11 01 24 AM" src="https://user-images.githubusercontent.com/599418/96905799-2d9dee80-1456-11eb-8831-c1d6c8070374.png">

**Comment by smaddox-sf** [comment]
Released last week
