### ISSUE TITLE
Pressing "Enter" on a selected field does not add the field to the query

### ISSUE THREAD

**Issue by mysticflute** [forcedotcom/soql-tooling#54]
**Code Builder or Desktop**:
Code Builder

**OS and version**:
Windows

**VS Code Version**:

**Browser Version (if applicable)**:
Edge

### Summary
When selecting fields in the SOQL Builder editor, a user should be able to use the arrow keys and pressing the enter key should add the field.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Tab to the Fields list
2. Use the arrow keys to select a field
3. Press enter

### Expected result

The field gets added to the list when pressing enter

### Actual result

The field is not added.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**:

**Comment by smaddox-sf** [comment]
Pressing 'enter' now adds the field
