### ISSUE TITLE
W-8580593: Starting a VSCode session with an expired authentication breaks SOQL editor

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#69]
Starting a VSCode session with an expired SFDX authentication breaks SOQL editor. It will not throw any error but it does not populate any data on the view. Switching to a valid authentication does not work either. The only solution is to switch to a valid authentication session and then restart VSCode.

<img width="1945" alt="VSCodesession_expiredauth" src="https://user-images.githubusercontent.com/1041842/98845885-2f2e5700-2403-11eb-9217-7f923d50132f.png">

**OS and version**: Mac OS 10.15.7

**VS Code Version**: 1.51.0

**Comment by jgellin-sf** [comment]
Fixed by https://github.com/forcedotcom/salesforcedx-vscode/pull/3049
