### ISSUE TITLE
W-8207738 - Run Query button does not indicate it is busy running your query

### ISSUE THREAD

**Issue by dehru** [forcedotcom/soql-tooling#75]
**Code Builder or Desktop**:
Desktop
**OS and version**:
OSX 10.14.6
**VS Code Version**:
1.52.0-insider
**Browser Version (if applicable)**:
NA
### Summary
When i click the Run Query button, it does not indicate that it is "busy" running the query.  If the query takes a long time, my tendency is to click it again, unsure if it captured my previous click.  This can result in multiple queries being run at once, with multiple result tabs displaying after the queries finally return.

This UX is especially brutal when your salesforce org has a lot of data and the query takes a while to run.  For instance, log into gus.

```
sfdx force:auth:web:login -r https://gus.my.salesforce.com -a gus
sfdx force:config:set defaultusername=<your gus email>@gus.com
```

### Steps To Reproduce:

1.  Log into gus
1.  Create a simple query like ```SELECT Id FROM ADM_Work__c```
1. Click Run Query
1. Notice the awkwardly long pause and the mental anguish as to whether anything is happening.

### Expected result

The Run Query button should disable and provide visible feedback to the user that is indeed carrying out their wishes.

### Actual result

The Run Query button just stays in it's current state, without any UX feedback that it has indeed received its orders to run the query.

### Additional information

![run-query](https://user-images.githubusercontent.com/599418/98972995-6b7bb900-24d0-11eb-9b80-d58f49b4e17a.gif)

**SFDX CLI Version**:
sfdx-cli/7.78.1-5a65d9dd2f linux-x64 node-v12.18.3

**Comment by smaddox-sf** [comment]
This is complete
