### ISSUE TITLE
Fields listbox readability

### ISSUE THREAD

**Issue by brpowell** [forcedotcom/soql-tooling#80]
**Is your feature request related to a problem? Please describe.**

It's a bit difficult to scroll through fields when there's a lot of them - especially if your eyes aren't so kind 👓 

**Describe the solution you'd like**

It'd be nice to either let the user resize, have the list box expand with the window size, or even just make it a little taller than it is now. Another small but really helpful improvement would be to alphabetize the fields.

**Comment by smaddox-sf** [comment]
Improvements to search the list released last week
