### ISSUE TITLE
Save dialog for exporting results

### ISSUE THREAD

**Issue by brpowell** [forcedotcom/soql-tooling#81]
**Is your feature request related to a problem? Please describe.**

The export results feature is opinionated about where to save the results - I'd like to be able to choose where they go. Another side effect of this is that you might overwrite your previous export by accident with a different query or just updated results of the same one.

**Describe the solution you'd like**

A save dialog might be a nice to have. [Save dialogs](https://code.visualstudio.com/api/references/vscode-api#2811) can have default location (like what already happens), but I can choose a different location and set the file name.

**Describe alternatives you've considered**

At the moment you can just rename the results or manually move them somewhere else if you want.

**Comment by jonnyhork** [comment]
@smaddox-sf Do we want to provide a default location in this case? Possibly the same location we currently save results?
I am asking so I can include the info in the WI.

**Comment by smaddox-sf** [comment]
> @smaddox-sf Do we want to provide a default location in this case? Possibly the same location we currently save results?
> I am asking so I can include the info in the WI.

@jonnyhork - Yes.  Let's default to the current location & current name

**Comment by smaddox-sf** [comment]
This has been added
