### ISSUE TITLE
W-8580564: Querying for related records introduces unnecessary data

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#85]
When running a query that gets data from a field on a related object it introduces data that was not queried for. 

Sample query:
```
Select childobjectname__c, fieldname__c, isCascadeDelete__c, z_ChildSObjectDescription__c, z_ChildSObjectDescription__r.Name, z_ChildSObjectDescription__r.isDeprecatedAndHidden__c  FROM z_ChildRelationship__c
```

<img width="865" alt="Screen Shot 2020-11-12 at 3 12 29 PM" src="https://user-images.githubusercontent.com/1041842/99007694-90d0ed00-24f9-11eb-9748-1457ee5dfeb6.png">

This causes the JSON result to include a new object in the result.
<img width="864" alt="related_query_json" src="https://user-images.githubusercontent.com/1041842/99007813-d42b5b80-24f9-11eb-96e4-417c25819f41.png">

It causes the CSV output to have a column with `[object Object]` value which hides all the data that was queried for.
<img width="860" alt="related_query_csv" src="https://user-images.githubusercontent.com/1041842/99007844-e1484a80-24f9-11eb-8651-e7f8f86d8587.png">

**Comment by jgellin-sf** [comment]
The columns in the SOQL Query Results and the CSV output certainly require changes in behavior, but I'm not sure about the JSON export. The information included in in the JSON export is consistent with the output of `sfdx force:data:soql:query --json`. Users familiar with the CLI JSON format may actually find this consistency useful.

@lcampos @amphro @smaddox-sf  What do you think?

**Comment by lcampos** [comment]
@jgellin-sf the priority is fixing the CSV export since that current behavior breaks the format. The json export can be kept as is for now since it is still valid json.
