### ISSUE TITLE
[W-8675840] Not providing enough error details to the user

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#86]
When a user runs an invalid query we show them the generic `Your query contains invalid or incomplete syntax. Fix the syntax errors and try again` but the library does provide enough information about the error. We should be surfacing that information to the user.

Sample query:
```
Select Id, Status, Location, Body from ApexLog
```

Library error message: 
```
Select Id, Status, Location, Body from ApexLog
                             ^
ERROR at Row:1:Column:30
No such column 'Body' on entity 'ApexLog'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

<img width="1942" alt="Screen Shot 2020-11-12 at 3 30 27 PM" src="https://user-images.githubusercontent.com/1041842/99009221-7b10f700-24fc-11eb-8fcd-73b088168ebe.png">

**Comment by smaddox-sf** [comment]
A fix has been released for this.
