### ISSUE TITLE
Closing multiple SOQL Builders throws errors

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#87]
Opening multiple SOQL Builders and then closing them throws an error when disposing of the Webview.

<img width="792" alt="Screen Shot 2020-11-12 at 3 36 45 PM" src="https://user-images.githubusercontent.com/1041842/99009569-15713a80-24fd-11eb-84f2-58de5ecabbff.png">

**Comment by smaddox-sf** [comment]
closing this one.  @lcampos - if this still happens for you, please let us know!
