### ISSUE TITLE
Option to add all the fields of the object to a query

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#89]
**Is your feature request related to a problem? Please describe.**
There should be an option in the SOQL Builder UI to use all the fields of an object in a query. Having to scroll and click on each field is not a good experience when an object has more than 5-10 fields.

**Comment by smaddox-sf** [comment]
Adding related feedback from #124:  (that issue included many topics, so breaking them out to individual threads)

select all fields, and select all non system fields, and all insertable fields (non system and non-formula) would be killer additions! 

Use cases for these:

* backup an object before i do something risky
* move data between orgs
* pull down sample test records into CSV for test.loadData
