### ISSUE TITLE
SOQL syntax highlighting is not working

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/soql-tooling#90]
Open a .soql file (using the Text Editor) and you'll see the query is not properly color coded. If you use VSCode's developer tools (Command palette > Developer: Inspect Editor Tokens and Scopes) you can verify that the query is not getting tokenized.

<img width="671" alt="Screen Shot 2020-11-12 at 4 25 55 PM" src="https://user-images.githubusercontent.com/1041842/99013198-d7781480-2504-11eb-80f5-463985831593.png">
<img width="603" alt="Screen Shot 2020-11-12 at 4 25 48 PM" src="https://user-images.githubusercontent.com/1041842/99013207-da730500-2504-11eb-9c8b-8fd5d43ac54d.png">
<img width="602" alt="Screen Shot 2020-11-12 at 4 25 39 PM" src="https://user-images.githubusercontent.com/1041842/99013213-dc3cc880-2504-11eb-873f-2686044b9098.png">

**Comment by smaddox-sf** [comment]
Syntax highlighting is working.  Let us know if it's not working for you!
